### PR TITLE
Add getter for categories in ExtMetaData

### PR DESCRIPTION
**Pull request by maskaravivek**
GPS and category information is required while constructing the `Media` object in commons.

### CODE REVIEW

**Comment by maskaravivek** [comment]
@dbrant Can you take a look at both my PRs. Once they are merged, I can merge commons' master with the backend-overhaul branch.

**Comment by dbrant** [comment]
Excellent.

**Comment by maskaravivek** [comment]
@dbrant Will you have to bump library's version? Let me know once you bump it. I can use the updated version.

**Comment by dbrant** [comment]
Yes, just merging a couple more of my own changes, and will bump the version shortly.

**Comment by dbrant** [comment]
@maskaravivek Done -- the library version is now `0.0.11`.

**Pull request merged**
